backend:
  name: github
  repo: abcalderon3/FFXIVPocketGuide
  branch: master
  base_url: https://us-central1-thinking-window-255219.cloudfunctions.net
  auth_endpoint: /ffxiv-pg-oauth/auth

publish_mode: editorial_workflow

media_folder: "assets/img"

collections:
  - name: "sb"
    label: "Stormblood"
    folder: "_posts/sb"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{patchNumber}}-{{fields.slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
