backend:
  name: test-repo

publish_mode: editorial_workflow

media_folder: "assets/img"

collections:
  - name: "sb"
    label: "Stormblood"
    folder: "_posts/sb"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{patchNumber}}-{{fields.slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}